/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaunchCreateRouteImport } from './routes/launch.create'
import { Route as ApiPublicTickRouteImport } from './routes/api/public/tick'
import { Route as ApiPublicRunCycleRouteImport } from './routes/api/public/run-cycle'

const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchCreateRoute = LaunchCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LaunchRoute,
} as any)
const ApiPublicTickRoute = ApiPublicTickRouteImport.update({
  id: '/api/public/tick',
  path: '/api/public/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunCycleRoute = ApiPublicRunCycleRouteImport.update({
  id: '/api/public/run-cycle',
  path: '/api/public/run-cycle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launch': typeof LaunchRouteWithChildren
  '/launch/create': typeof LaunchCreateRoute
  '/api/public/run-cycle': typeof ApiPublicRunCycleRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launch': typeof LaunchRouteWithChildren
  '/launch/create': typeof LaunchCreateRoute
  '/api/public/run-cycle': typeof ApiPublicRunCycleRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/launch': typeof LaunchRouteWithChildren
  '/launch/create': typeof LaunchCreateRoute
  '/api/public/run-cycle': typeof ApiPublicRunCycleRoute
  '/api/public/tick': typeof ApiPublicTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launch'
    | '/launch/create'
    | '/api/public/run-cycle'
    | '/api/public/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/launch'
    | '/launch/create'
    | '/api/public/run-cycle'
    | '/api/public/tick'
  id:
    | '__root__'
    | '/'
    | '/launch'
    | '/launch/create'
    | '/api/public/run-cycle'
    | '/api/public/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaunchRoute: typeof LaunchRouteWithChildren
  ApiPublicRunCycleRoute: typeof ApiPublicRunCycleRoute
  ApiPublicTickRoute: typeof ApiPublicTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/create': {
      id: '/launch/create'
      path: '/create'
      fullPath: '/launch/create'
      preLoaderRoute: typeof LaunchCreateRouteImport
      parentRoute: typeof LaunchRoute
    }
    '/api/public/tick': {
      id: '/api/public/tick'
      path: '/api/public/tick'
      fullPath: '/api/public/tick'
      preLoaderRoute: typeof ApiPublicTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-cycle': {
      id: '/api/public/run-cycle'
      path: '/api/public/run-cycle'
      fullPath: '/api/public/run-cycle'
      preLoaderRoute: typeof ApiPublicRunCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LaunchRouteChildren {
  LaunchCreateRoute: typeof LaunchCreateRoute
}

const LaunchRouteChildren: LaunchRouteChildren = {
  LaunchCreateRoute: LaunchCreateRoute,
}

const LaunchRouteWithChildren =
  LaunchRoute._addFileChildren(LaunchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaunchRoute: LaunchRouteWithChildren,
  ApiPublicRunCycleRoute: ApiPublicRunCycleRoute,
  ApiPublicTickRoute: ApiPublicTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
